language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10
      env: BUILD_TYPE=Release

    - os: linux
      addons: { apt: {
        packages: [g++-7, libboost1.55-all-dev],
        sources: [ubuntu-toolchain-r-test, boost-latest] } }
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" BUILD_TYPE=Release

    - os: linux
      addons: { apt: {
        packages: [g++-7, libboost1.55-all-dev, lcov],
        sources: [ubuntu-toolchain-r-test, boost-latest] } }
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" BUILD_TYPE=Coverage GCOV=gcov-7

    - os: linux
      addons: { apt: {
        packages: [clang-6.0, libstdc++-7-dev, libboost1.55-all-dev],
        sources: [llvm-toolchain-trusty-6.0, ubuntu-toolchain-r-test, boost-latest] } }
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Release

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ci/travis-build.sh

after_success:
  - ci/travis-coverage.sh

notifications:
  email: false
